### ISSUE TITLE
Write Wiki about your understanding of concepts

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/care_taker_robot#12]
- Add about basic ros workings on this [link](https://github.com/noshluk2/care_taker_robot/wiki/Lesson-%23-1-:-Understanding-Project-WorkFlow)

**Comment by hibataimoor** [comment]
Completed on the [link](https://github.com/noshluk2/care_taker_robot/wiki/Lesson-%23-1-:-Understanding-Project-WorkFlow).

**Comment by noshluk2** [comment]
nice job
