### ISSUE TITLE
Translating cmd_vel to Motor Pwm Pins

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/care_taker_robot#2]
- Driving Robot after Subscribing cmd_vels published form laptop
- Set frequency Fast Enough for robot to be responsive 
- Resource [Link](https://github.com/noshluk2/ROS2-Raspberry-PI-Intelligent-Vision-Robot/blob/raspberrypi/vision_rpi_bot/vision_rpi_bot/cmd_to_pwm_driver.py)

**Comment by hibataimoor** [comment]
I tried running the code on the Raspberry Pi but ran into errors on the first and second lines. I think I have to install ROS first.

**Comment by hibataimoor** [comment]
I spent around 4 hours trying to install ROS...But it didn't work. It says : 
"failed to fetch metadata: exit status 2
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/"

However, the buildx component is the latest version available.

**Comment by hibataimoor** [comment]
I am installing using the steps on: https://docs.ros.org/en/humble/How-To-Guides/Installing-on-Raspberry-Pi.html .
Raspberry Pi OS with ROS 2 in docker.

**Comment by noshluk2** [comment]
Install using this

https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html



Perform basic installation

**Comment by hibataimoor** [comment]
Finished.
