### ISSUE TITLE
Robot Reverse Clock wise Rotation with basic PWM

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/care_taker_robot#3]
- Write node and test

**Comment by hibataimoor** [comment]
Completed.

**Comment by noshluk2** [comment]
I re opened it : 
You push your code with issue number in commit message e.g #3 for this issue and then close it . So i can see your code

**Comment by hibataimoor** [comment]
https://github.com/noshluk2/care_taker_robot/tree/master

**Comment by hibataimoor** [comment]
https://github.com/noshluk2/care_taker_robot/tree/master
