### ISSUE TITLE
Links to Hardware

### ISSUE THREAD

**Issue by hibataimoor** [noshluk2/care_taker_robot#4]
Hardware Questions

**Comment by hibataimoor** [comment]
I have a 12v battery at home, but I am not sure what do we need portable battery for the Robot.

https://www.amazon.com/ML7-12-Battery-Mighty-Brand-Product/dp/B00K8V30D0/ref=sr_1_5_pp?crid=41DINLHF4IIG&keywords=12v%2Bbattery&qid=1695078790&sprefix=12v%2Bbattery%2Caps%2C210&sr=8-5&th=1
Look at this picture , I cant figure out the battery they are using
http://www.yahboom.net/study/ROSMASTER-X3
Some accessories for this chasis can be found here too https://category.yahboom.net/collections/ros-accessories

- Right now we have Chasis, Robotic Arm(Forgot to show you last week) , Raspberry Pi , some motor drivers

**Comment by noshluk2** [comment]
They are using Lipo Battery 
https://www.amazon.com/Battery-3300mAh-Strong-Capacity-Batteries/dp/B0B56HRKR8?th=1

And this battery charger as well 
https://www.amazon.com/Compact-Balance-Helicopter-Airplane-Multirotor/dp/B09SFGB5P9/ref=sr_1_10?crid=1S9Z7NFZKB159&keywords=11.1V+lipo+charger&qid=1695201206&sprefix=11.1v+lipo+char%2Caps%2C385&sr=8-10

**Comment by hibataimoor** [comment]
I think we need to have an hardware diagram that we can follow.

**Comment by noshluk2** [comment]
True , Kindly share one in block diagram how your hardware is wired. 
Have you done encoders ?

**Comment by hibataimoor** [comment]
I mean the full project diagram like this 
![image](https://github.com/noshluk2/care_taker_robot/assets/96356477/f769a586-b708-47c9-b16c-4d860d2deee6)

**Comment by noshluk2** [comment]
Kindly upload a document in wiki about your robot connections and pin numbers 
- All sensors
- Encoders
- Motor and its PWM pins
@hibataimoor
