### ISSUE TITLE
Motor Conection Testing 

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/care_taker_robot#5]
- Motor Connection
- Robot Driving Code
- Drive Robot 
-

**Comment by hibataimoor** [comment]
Test 2 Motors with 9V battery yesterday and 12V battery today but no luck. I have some some other motors without encoders and they are running with 12V battery. Need help there are 2 types of configuration available. Getting conflict information about the pins.
Looks at this , this image is from documentation
![image](https://github.com/noshluk2/care_taker_robot/assets/96356477/19aeac74-316b-41fe-955a-58b2f5fa87fa)
but another documentation has this
![image](https://github.com/noshluk2/care_taker_robot/assets/96356477/0023154a-875b-47d1-b050-ccb47f67152f)

**Comment by noshluk2** [comment]
On there website there are already made connectors 
https://www.youtube.com/watch?v=jSDqCbaGA40&ab_channel=YahboomTechnology
if you can get them and see the controller boards as well

**Comment by hibataimoor** [comment]
![image](https://github.com/noshluk2/care_taker_robot/assets/96356477/2abf67cc-e1ee-43eb-9ec3-f45f3d7197c3)
It worked with this configuration but in opposite direction. so the red means M+ but here its opposite.. Red cable is A (Encoder output), anyways I will check all motors and assemble the chasis again. 

Next question is hardware diagram. one option is to buy stuff like motor driver , main board from yahboom or buy generic motor driver. I dont know if we can discuss it over the phone or in the next session.

**Comment by noshluk2** [comment]
If direction is oppiste , change pins in code it will make it work .

**Comment by noshluk2** [comment]
I am re-opening this as you have not pushed the code here so i can very that this issue is solved .

**Comment by hibataimoor** [comment]
https://github.com/noshluk2/care_taker_robot/tree/MotorCode
