### ISSUE TITLE
Read Encoders and find direction of motion

### ISSUE THREAD

**Issue by noshluk2** [noshluk2/care_taker_robot#7]
- Read encoders on RPI using interrutps ( software  process )
- Calculate how many values are generated in one revolution of the robot 
- Drive wheels with fixed revolutions and test accuracies

**Comment by hibataimoor** [comment]
Question: Why everyone is using Arduino for working with Encoders ?, all the videos on YouTube are with Arduino. I hardly find anything with Raspberry Pi. Still, I will try to connect it to GPIO pins and get the value.

**Comment by hibataimoor** [comment]
https://github.com/noshluk2/care_taker_robot/blob/master/motor_encoder.py
